from collections.abc import Iterable, Sequence
from composify.core.rules import Rule


class RuleRegistry:
    def add_rule(self, rule: Rule) -> None: ...
    def add_rules(self, rules: Iterable[Rule]) -> None: ...
    def get_rules(self, type_info: type) -> Sequence[Rule]: ...

